intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import libbuild2 = build2%lib{build2}

import impl_libs += $libbuild2 # Implied interface dependency.

lib{build2-rust}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

obja{*}: cxx.poptions += -DLIBBUILD2_RUST_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBBUILD2_RUST_SHARED_BUILD

# Export options.
#
lib{build2-rust}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{build2-rust}: cxx.export.poptions += -DLIBBUILD2_RUST_STATIC
libs{build2-rust}: cxx.export.poptions += -DLIBBUILD2_RUST_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{build2-rust}: bin.lib.version = "-$version.project_id"
else
  lib{build2-rust}: bin.lib.version = "-$version.major.$version.minor"

# Embed the build system core version as our load suffix.
#
# Get the version as exported by the lib{build2} target falling back to the
# running build system version if unable to (installed lib{build2}).
#
iv = ($project($libbuild2) == [null]     \
      ? $($libbuild2: interface_version) \
      : [null])

ifn $iv
  iv = $build.version.interface

libs{build2-rust}: bin.lib.load_suffix = "-$iv"

# Install into the libbuild2/rust/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libbuild2/rust/
  install.subdirs = true
}
